dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.2
  - OpenZeppelin/openzeppelin-contracts@4.4.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.2"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1"

networks:
  default: "development"
  development:
    verify: False
  rinkeby:
    verify: True
  goerli:
    verify: True
  